import { _query } from './index.js';
import { set_cookie } from './cookies.js';
import { filter_input } from './sql_shield.js';

function generate_sid() { // @fixme Consider obfuscating this
    return Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
}

async function validate_login(event) {
    event.preventDefault(); // Prevent page from reloading
    const username = document.getElementById('form-username').value;
    const password = document.getElementById('form-password').value;

    username = filter_input(username);
    password = filter_input(password);

    const queryText = `SELECT * FROM users WHERE username = '${username}' AND password = '${password}'`;
    const result = await _query(queryText);

    console.log(result);

    if (result === null) {
        console.error("Error validating login");
        return false;
    } else {
        if (result.length === 0) {
            console.error("Invalid username or password");
            return false;
        } else {
            console.log("Login successful");
            const sid = generate_sid();

            // No need to filter sid, as it is generated by the server
            
            set_cookie('sid', sid, 1);
            await _query(`UPDATE users SET sid = '${sid}' WHERE username = '${username}'`);

            window.location.href = '/pages/index.html'; // Send the user back to the main menu page

            return true;
        }
    }
}

document.getElementById('login-form').addEventListener('submit', validate_login);
